name: downloader_notifier
description: "A floating bar for real-time download progress updates, designed for both Android and iOS."
version: 1.0.2
homepage: https://inidia.app
repository: https://github.com/Nialixus/downloader_notifier
funding:
  - https://ko-fi.com/nialixus
# screenshots:
#   - description: "Downloader Notifier Logo"
#     path: logo.png
topics:
  - utility
  - downloader
  - notification
platforms:
  android:
  ios:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  fl_downloader: ^2.0.2
  flutter:
    sdk: flutter
  flutter_in_app_pip: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0